version: "3"

services:
  # app:
  #   container_name: twittersentimentanalysis_app
  #   build: "."
  #   # command: >
  #   #   python app.py
  #   # env_file:
  #   #   - .env
  #   # ports:
  #   #   - "8000:8000"
  #   volumes:
  #     - ./app:/app

  zookeeper:
    container_name: twittersentimentanalysis_zookeeper
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    expose:
      - "2181"

  kafka:
    container_name: twittersentimentanalysis_kafka
    image: wurstmeister/kafka:2.12-2.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      - "KAFKA_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      - "KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9092"
      - "KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE"
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_CREATE_TOPICS=tweets:1:1"
      - "KAFKA_LOG_DIRS=/tmp/kafka-logs"
    volumes:
      - ./persistence/kafka:/tmp/kafka-logs

  # grafana:
  #   container_name: twittersentimentanalysis_grafana
  #   image: grafana/grafana:6.5.2
  #   environment:
  #     - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource"
  #     - "GF_AUTH_ANONYMOUS_ENABLED=true"
  #     - "GF_AUTH_ANONYMOUS_org_name=Main Org."
  #     - "GF_AUTH_ANONYMOUS_org_role=Admin"
  #   ports: 
  #     - "3000:3000"
    volumes:
      - ./persistence/grafana:/var/lib/grafana

networks:
  default:
    external:
      name: twittersentimentanalysis_network